### ISSUE TITLE
Skip automatic release without new commits

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/utils#19]
## Description
A new release should not be created if there are no changes since the previous one (ref: https://github.com/projectdiscovery/team-backlogs/issues/228)

**Comment by ehsandeep** [comment]
I was looking at this other day and found something like below can be used to get commit count from last tagged release, we probably need to use this information in next step to run only when `get_commit > 0`

```yaml
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Commit Count
        id: get_commit
        run: git rev-list  `git rev-list --tags --no-walk --max-count=1`..HEAD --count
```
